---
title: "p8105_hw5_qz2527"
author: "kindle zhang"
date: "2023-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1


* first we import the data and describe it concisely.

```{r}
homi_data = read_csv("./data_file/homicide-data.csv")

head(homi_data, 5)
summary(homi_data)
```
* tidy the data and make a series of operation upon it

```{r}
homi_data =
  homi_data |>
  janitor::clean_names() |>
  mutate(city_state = str_c(city, ", ", state))

homi_by_city =
  homi_data |>
  drop_na(disposition) |> 
  group_by(city_state) |>
  mutate(
    unsolved_homi = case_match(
      disposition,
      "Closed without arrest" ~ 1,
      "Open/No arrest" ~ 1,
      .default = 0
    )
  ) |>
  summarise(total_homi = n(),
            unsolved_homi = sum(unsolved_homi))

homi_by_city
```

<font color = red>according to the result gained above , we can summarize the total homicides and unsolved homicides by each city.</font>

* use `prop.test` function to estimate the proportion of homicides that are unsolved

```{r}
homi_Bal = 
  homi_by_city |> 
    filter(city_state == "Baltimore, MD") 

result_Bal = 
  prop.test(
    x = homi_Bal$"unsolved_homi",
    n = homi_Bal$"total_homi",
    p = NULL,
    alternative = "two.sided"
  )

result_Bal |> 
  broom::tidy() |> 
  select(estimate, conf.low, conf.high) |> 
  rename(esti_prop = estimate)
```

* loop the function for each city

```{r, warning = FALSE}
prop_by_city = 
  homi_by_city |>
    mutate(prop_test_result =
             map2(unsolved_homi,
                  total_homi,
                  ~ prop.test(x = .x, n = .y))) |>
    mutate(estimate_result =
             map(prop_test_result, broom::tidy)) |>
    unnest(estimate_result) |>
    select(city_state, estimate, conf.low, conf.high)

head(prop_by_city)
```

* create a plot

```{r}

```

